Azure/osm-azure

- charts/osm/templates/osm-deployment.yaml
- charts/osm/values.yaml
Changes Fluent Bit container image to pull v1.6.2 from MCR rather than 1.5 Docker
> chore(charts): Update Fluent Bit to pull image from MCR

- charts/osm-arc/Chart.yaml
- charts/osm-arc/values.yaml
- test/bats/test.bats
Creating this to test with osm chart locally until 0.5.1 release is cut.
> [WIP] Update osm dependency chart to 0.6.0-rc.1

- .pipelines/e2e-aks-arc.yaml
- .pipelines/templates/acr-cleanup.yaml
- .pipelines/templates/aks-cleanup.yaml
- .pipelines/templates/aks-setup.yaml
- .pipelines/templates/publish-helm-chart.yaml
- Makefile
- scripts/add-extension.sh
Redirect bash output to /dev/null for steps in CI pipeline that reveal sensitive information such as tenantID and staging registry. Most of this can be hidden by setting the variable types to "secrets" in the ADO UI, but some steps (such as the ACR cleanup) still leak information we want to keep hidden. Setting variables to "secret" also require you to explicitly list them as env variables in the scripts you use them in, so I also needed to add that as well.
> Hide output revealing az account and registry information from user

- .pipelines/e2e-aks-arc.yaml
- test/bats/test.bats
Only arc-specific tests only run if we are testing on arc cluster with osm chart pushed to staging ACR, as opposed to a kind cluster with osm chart installed direcly.
> parameterized test.bats

- .pipelines/e2e-aks-arc.yaml
- test/bats/test.bats
Fixes failing logic for arc-cluster-specific tests by moving conditionals within test blocks. Flips boolean to default to expect an arc cluster. Skipped tests will now show up as:
```
ok 8 azure-arc deployments have succeeded # skip arc cluster-specific test
ok 9 chart version on cluster matches checkout tag # skip arc cluster-specific test
ok 10 openservicemesh.io/ignore is true in azure-arc # skip arc cluster-specific test
```
> tests: fix logic for parameterized tests

- charts/osm-arc/values.yaml
Removed connectVault from values.yaml as this variable is no longer used in Upstream chart.
> Removed ConnectVault variable

- Makefile
Given that we have a non-trivial amount of bash scripts here - it would be good to add `shellcheck`, which will point out issues and how to fix these.
This can be run with `make shellcheck` and will give hints on fixing common Bash issues.
Next step: fix bash issues `shellcheck` discovers.
Signed-off-by: Delyan Raychev <delyan.raychev@microsoft.com>
> Makefile: Add shellcheck target

- scripts/add-extension.sh
- scripts/connect-to-arc.sh
- scripts/delete-extension.sh
- scripts/enable-arc-feature.sh
- scripts/publish-chart.sh
- scripts/update-extension.sh
This PR leverages [shellcheck](https://www.shellcheck.net/) introduced with https://github.com/Azure/osm-azure/pull/66 and addresses some of the suggestions `make shellcheck` produces.
In this PR:
- Double quoting Bash variables to prevent globbing and word splitting
- Split long bash statements into multiple lines
- Augmenting some of the `echo` statements with additional context
No functional code changes.
> Double quoting Bash variables to prevent globbing and word splitting

- .pipelines/e2e-aks-arc.yaml
- .pipelines/e2e-job.yaml
- .pipelines/templates/package-helm-chart.yaml
- .pipelines/templates/publish-helm-chart.yaml
- .pipelines/templates/run-upstream-e2e.yaml
- test/bats/test.bats
This PR uses the current chart version instead of hardcoding the image.tag as 0.1.0. This current chart version is also used to checkout the appropriate upstream branch instead of checking out the branch corresponding to the current version in main.
> Fix chart version

- charts/osm-arc/values.yaml
- scripts/add-extension.sh
- scripts/update-extension.sh
Context: A `controllerLogLevel` variable was added upstream that controls which level of logs are emitted by the controller. This takes away the need for Fluent Bit to filter on log level. [This PR](https://github.com/openservicemesh/osm/pull/2726) in OSM removes Fluent Bit logLevel variable and filters in favor of the controllerLogLevel variable. In upstream, the controller log level is set to "info".
This PR overrides controller log level to "error" to match the previous behavior of `fluentBit.logLevel`.
Signed-off-by: Sanya Kochhar <kochhars@microsoft.com>
> chore(logs): use and override controllerLogLevel instead of fluentBit.logLevel

- .github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md
- .github/pull_request_template.md
* Default PR template similar to OSS PR template, auto populates when you open a PR
* Release PR template can be used by adding `?expand=1&template=release_pull_request_template.md` to the PR URL during creation or copying the raw template
> chore(github): add PR templates for default and release PRs

- charts/osm-arc/values.yaml
Signed-off-by: Rita Zhang <rita.z.zhang@gmail.com>
This PR adds `app.kubernetes.io/component: osm-controller` labels to osm pods so we can use them to scrape osm metrics. 
NOTE: This PR depends on upstream release of v0.8.3-rc.1 
Pending #87 
- Metrics                [X]
No
> feat(chart): add pod label

- .pipelines/upgrade-e2e-job.yaml
**Description**: Currently the upgrade job runs after you merge a PR to main. I changed the trigger so that this only happens on PRs merged to main where the Chart.yaml was edited. 
> Change trigger for upgrade job

- Makefile
- docs/get-started.md
This PR peels-off the bash scripts from the Getting Started doc to use the underlying `az` CLI commands instead.
> docs: refactor the Getting Started doc

- .pipelines/templates/get-latest-tag.yaml
**Description**: This PR fixes a bug where the upgrade-e2e job fetches the 2nd most recent stable release, instead of the most recent stable release, for non-rc tags. 
- Performance            [X]
> fix logic for prev tag for upgrade job

- charts/osm-arc/values.yaml
**Description**: Add field in the values.yaml called "testedDistros," which az k8s-extension will fetch to notify the user whether their current k8s distros has been tested for osm-arc. https://github.com/Azure/azure-cli-extensions/pull/3336. Note that az connectedk8s doesn't validate whether the current distro is canonical yet. The list of all the return values for kubernetes_distro can be found here: https://github.com/Azure/azure-cli-extensions/blob/0bf8ef35e22d520708dc3fc99179f3f2e1a87332/src/connectedk8s/azext_connectedk8s/custom.py#L436
- …
> Add field for validated distros in values.yaml

- charts/osm-arc/templates/osm-label.yml
**Description**: Set the nodeselector to Linux for the osm-label job. Without this, osm-arc will not install successfully on AKS-HCI clusters, as the job will try to run on a windows container and fail. 
> Set nodeselector to linux

- .pipelines/templates/checkout-upstream-repo.yaml
- .pipelines/templates/run-upstream-e2e.yaml
- .pipelines/templates/upgrade-CRDS.yaml
- .pipelines/upgrade-e2e-job.yaml
**Description**: The CRD upgrade step for the upgrade-e2e-job was running the CRD cleanup script from the current upstream branch, instead of the upstream branch corresponding to the previous release which was installed prior to the upgrade. This fix ensures that the CRDs are deleted from the "previous" branch, and the installed from the "current" branch. 
- Does this change contain …
> Fix crd upgrade step

- .pipelines/aks-addon-nightly/e2e-aks-addon-jobs.yaml
- .pipelines/templates/run-upstream-e2e.yaml
**Description**: Changed the branch that the upstream e2es are run from, so that they are run from release branches instead of checking out tags. Note that the logic for determining which branch to run works slightly differently for AKS add-on vs the osm-arc PR gate. OSM-Arc cannot use a UI variable for the release branch, because PRs that update the chart to different versions (ex from v0.8.4 to v0.9.0) will need to run on a different branch than all the other PRs currently in progress with v0.8.4. The AKS addon job can use a UI variable because it doesn't need to worry about version differences between PRs. 
- Security …
> Change upstream e2e branch

- .pipelines/osm-arc-prod.yaml
- .pipelines/templates/add-arc-extension.yaml
- .pipelines/test-osm-arc-prod.yaml
- scripts/add-extension.sh
**Description**: Add a new, manually triggered pipeline to test osm-arc in prod. Extension version and release train will be passed in as UI configurable variables. 
> Add job to test osm-arc in prod

- tools/helm/Dockerfile
**Description**: Install the most up to date libgmp10 version in the helm cli image to address security vulnerability CVE-2021-43618, which is causing the nightly image scan job to fail. 
> Fix libgmp10 security vulnerability in helm cli image

- .pipelines/nightly-image-scan/image-scan.yaml
- .pipelines/pr-job/e2e-job.yaml
**Description**: Change trigger for pr-job so it doesn't get triggered for changes to conformance or helm-cli images. Change trigger for the image-scan job so that it only gets triggered post-merge for changes to conformance or helm image. 
> Change triggers for pr-job and image-scan

- conformance/plugins/osm-arc/conformance.yaml
- conformance/plugins/osm-arc/osm_arc_conformance.sh
**Description**: Skipping the e2e_tcp_server_first_test in the upstream repo on RKE clusters, as the `buf.ReadFrom(logStream)` command is hanging for some reason, even though `kubectl logs` and `kubectl logs -f` are both able to view logs from the client pod. Tried changing the method to do a `Do()` and `DoRaw()` instead of `Stream()` but the command was still hanging and was unable to get any type of response. This test (both with `Stream()` and `Do()`) was passing on AKS and other distributions, however, so I think we should be safe to skip on RKE. 
- Security               [ …
> Skip tcp-server-first e2e on RKE

- .github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md
**Description**: Add a step to the release pull request guide to ensure that OSM and envoy images are available in MCR for multiple architectures (for third party dependencies like grafana/jaeger/prometheus this may not always be necessary / possible) .
- Other                  [X]
> Update release guide for multi-arch

- .pipelines/pr-job/e2e-aks-arc.yaml
- .pipelines/templates/publish-helm-chart.yaml
- .pipelines/templates/register-extension.yaml
- scripts/register-extension.sh
**Description**: Add register-extension script and add to CI to register Arc extension for the chart that's pushed to staging. This registers the extension by generating an access token and making an `AZ REST` PUT request to the Arc registration API.
> Add register-extension script and call in CI

- .pipelines/templates/run-upstream-e2e.yaml
**Description**: Skipping Ingress backend e2e both for AKS addon nightly job and OSM-Arc CI until bug is resolved. 
Context: https://github.com/kubernetes/ingress-nginx/issues/8518
> Temporarily skip ingressbackend e2e for AKS-addon and OSM-Arc

- charts/osm-arc/templates/_helpers.tpl
- charts/osm-arc/templates/azure-extension-identity.yaml
- charts/osm-arc/templates/metrics-agent-deployment.yaml
- charts/osm-arc/templates/metrics-config.yaml
- charts/osm-arc/templates/metrics-rbac.yaml
- charts/osm-arc/values.yaml
- test/bats/test.bats
Signed-off-by: Sanya Kochhar <kochhars@microsoft.com>
**Description:**
* Adds a metric agent pod that helps send metrics to MDM
using Telegraf as a pipeline.
* prom-mdm-converter container helps convert Prometheus
metrics into statsd format for consumption by MDM.
**Testing done:**
- Tested that kube-inventory outputs match resource limits set on pods
- Tested setting metrics namespace as the region of extension installation
- Bats tests added for basic readiness of metrics pods
Follow up: metrics in a proxy environment
- New Functionality      [x]
- Metrics                [x]
- Performance …
> metrics: add metrics agent to send metrics via telegraf

- conformance/plugins/osm-arc/conformance.yaml
- conformance/plugins/osm-arc/osm_arc_conformance.sh
**Description**: Fix go env variable setting, which was causing the `make build-osm` step to fail in the conformance test plugin. 
> Fix go env conf test image

- .pipelines/aks-addon-nightly/e2e-aks-addon-jobs.yaml
- .pipelines/templates/aks-setup.yaml
This is needed for the AKS addon nightly job, as AKS add-on releases are now synced with specific minimum k8s version cutoffs.
> Make k8s.version configurable

- conformance/plugins/osm-arc/conformance.yaml
- conformance/plugins/osm-arc/osm_arc_conformance.sh
**Description**: Fix osm-arc conformance plugin for v1.1.1-1. Previously, the conformance test plugin was not properly handling osm-arc versions with a "-", which caused it to fail some e2es such as the client-server and egress tests, since the CTR_TAG was invalid for the test images used in those e2es. 
- Does this change contain code from or inspired by another project? If so, did …
> Fix conf plugin v1.1.1-1

- conformance/plugins/osm-arc/conformance.yaml
- conformance/plugins/osm-arc/osm_arc_conformance.sh
**Description**: Update the conformance test plugin to rerun tests that failed. Retry logic parses and formats XML output accordingly to rerun failed tests. 
Tested locally for both passing and failing scenarios (deliberately triggered failures). 
> Add retry logic to conformance test plugin

- .pipelines/pr-job/e2e-job.yaml
- .pipelines/upgrade-job/upgrade-e2e-job.yaml
Signed-off-by: nshankar <nshankar@microsoft.ghe.com>
**Description**: Fix CI triggers so that the pr-e2e-arc and upgrade-e2e-arc jobs get triggered for PRs against release branches. 
> Fix ci triggers for release branches

- conformance/plugins/osm-arc/osm_arc_conformance.sh
- scripts/install-k8s-extension.sh
The upgrade e2e pipeline is failing due to issues with the k8-extension. Pinning version to v1.3.5
**Passing upgrade-e2e-arc pipeline with change**: https://dev.azure.com/AzureContainerUpstream/OpenServiceMesh/_build/results?buildId=77849&view=logs&j=9de9e2b7-8af7-5276-a88f-b4157127a375&t=113d0cda-a20a-5c06-6ada-e4487e3a394d
- Tests                  [x]
- Does this change contain code from or inspired by another project? If so, did you notify the …
> fix: pin k8s-extension version to 1.3.5
