scripts/get-started.md, scripts/publish-chart.sh
Changed scripts to include deployment with oras as opposed to "helm push"
=> modified_script

.env.example, scripts/add-extension.sh
This PR parameterizes the release_namespace for the osm-azure helm chart
=> Parameterize release namespace for osm-azure chart

.pipelines/e2e-aks-arc.yaml, .pipelines/e2e-job.yaml, .pipelines/templates/acr-cleanup.yaml, .pipelines/templates/add-arc-extension.yaml, .pipelines/templates/install-helm3.yaml, .pipelines/templates/install-oras.yaml, .pipelines/templates/package-helm-chart.yaml, .pipelines/templates/publish-helm-chart.yaml, scripts/add-extension.sh, test/bats/test.bats
In the first PR I created to create AZ pipelines I wasn't actually able to run the pipelines to test. I'm opening this PR both to test the pipeline in an actual PR gate as well as change the way we package the helm chart, so that every chart in the PR has a unique tag. This way, there is no mix-up when we the e2es pull the helm chart down from staging ACR and install onto the cluster to run validation tests.
=> Edits to test pipeline and make unique tags

charts/osm-arc/values.yaml
* Updates values per new variables names
* Overrides values that diverge between oss and osm-azure
* Bumps fluent bit image to 1.6.4 to support http proxy
=> fluent bit: sync fluent bit values and chart version with oss

.env.example, scripts/add-extension.sh
Signed-off-by: Kalya Subramanian <kasubra@microsoft.com>
This PR parameterizes the extension name and version using the .env file. Defaults are set in the add-extension script
=> ref: Parameterize extension name and version

docs/delete-extension.md, docs/get-started.md, scripts/delete-extension.sh
Create script to delete OSM arc extension.
Adds docs for delete experience
[MERGED]Depends on upstream PR for documentation: https://github.com/openservicemesh/osm/pull/2267
=> Add delete-extension.sh to clean up osm arc extension

.pipelines/templates/acr-cleanup.yaml
Signed-off-by: Rita Zhang <rita.z.zhang@gmail.com>
=> Update chart name in cleanup script

charts/osm-arc/values.yaml
Signed-off-by: Kalya Subramanian <kasubra@microsoft.com>
Fixes #46
=> ref(chart): Keeps debug server disabled by default

.pipelines/templates/add-arc-extension.yaml, scripts/add-extension.sh
Parameterized connected k8s version as a UI configurable variable.
=> paramaterized connectedk8s version

Makefile, docs/testing-guide.md
* Refactor makefile targets to create explicit functionality for local testing
* Create testing guide for local e2e testing
Resolves #29
=> testing: refactor makefile and document local testing

charts/osm-arc/values.yaml
=> Change envoy version to 1.17

charts/osm-arc/Chart.yaml
=> Updated to 0.7.0

charts/osm-arc/Chart.yaml, charts/osm-arc/values.yaml
I have updated the Helm chart:
=> Create tag for 0.8.0-rc.2

charts/osm-arc/Chart.yaml
2. fluent-bit and envoy images of versions listed in osm-arc/oss values.yaml
=> Update version and upstream dependency to 0.8.2

.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md
=> Add checkbox for 3 approvals

charts/osm-arc/templates/osm-label.yml, charts/osm-arc/values.yaml
Signed-off-by: Kalya Subramanian <kasubra@microsoft.com>
Configure anyuid SCC for osm-label job to run on OpenShift
Inspired by https://github.com/Azure/azure-policy-kubernetes/pull/149/files
=> feat(openshift): Configure osm-label to work on OpenShift

.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md, charts/osm-arc/values.yaml, docs/logs.md, test/bats/test.bats
Signed-off-by: Sanya Kochhar <kochhars@microsoft.com>
**Description**: Per the decision to no longer send logs to Log Analytics, this change:
* makes Fluent Bit default disabled
* removes controller log level override (defaults to info as in upstream)
* removes fluent bit test
* removes logs.md doc
- Other                  [x]
no
=> chore(charts): default disable fluent bit

scripts/update-extension.sh
**Description**:  Edit the update-extension script to also use az k8s-extension. 
No
=> edited update extension script

charts/osm-arc/Chart.yaml
- Does this change contain code from or inspired by another project? If so, did you …
=> Update version to v0.8.3

scripts/install-connectedk8s.sh, scripts/install-k8s-extension.sh
**Description**: Use the published versions of `k8s-extension` and `connectedk8s` 
=> Use public az extensions

.pipelines/aks-addon-nightly/e2e-aks-addon-jobs.yaml, .pipelines/aks-addon-nightly/e2e-aks-addon.yaml, .pipelines/e2e-aks-arc.yaml, .pipelines/upgrade-e2e-job.yaml
**Description**: Change agent pool to new agent pool to unblock CI. 
=> Change agent pool

charts/osm-arc/Chart.yaml
- Does this change contain code …
=> Update to 0.9.1-rc.1

charts/osm-arc/Chart.yaml
- Does this change contain code from or inspired by another project? If so, did you …
=> Update to 0.9.1

charts/osm-arc/templates/validate-single-mesh.yml
**Description**: Add nodeSelector for the validate_single_mesh preinstall job so that the job only runs on linux nodes. 
=> Add nodeselector for validate_single_mesh

charts/osm-arc/Chart.yaml
- Other                  [x]
No.
=> Create 0.9.2 release

conformance/plugins/osm-arc/conformance.yaml, conformance/plugins/osm-arc/osm_arc_conformance.sh
**Description**: Skip OSM reinstall test for conformance test since it uninstall and reinstalls OSM via OSM CLI. 
=> Update conf test image

.pipelines/conformance-test-job/push-osm-arc-conf-plugin.yaml
**Description**: Fix the conformance test image pipeline. 
=> Fix conf image pipeline

.pipelines/aks-addon-nightly/e2e-aks-addon-jobs.yaml
**Description**: Add helm install step to AKS addon nightly job to unblock the e2e failures. 
=> Add helm install to AKS nightly

tools/helm/Dockerfile
**Description**: Add a Dockerfile for an image with helm & jq, which we will push to MCR and use in our osm-arc pre-install validation. 
=> Add dockerfile for helm image

charts/osm-arc/templates/validate-single-mesh.yml, charts/osm-arc/values.yaml
**Description**: Change the image registry for kubectl and helm in pre-install job from dockerhub to ACR / MCR. 
https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/12522300/
=> Change pre-install image registry

conformance/plugins/osm-arc/Dockerfile, conformance/plugins/osm-arc/conformance.yaml, tools/helm/Dockerfile
**Description**: Fix OS security vulnerabilities in helm-cli image and osm-arc-conformance image. Will follow up on this PR with a nightly job to scan images for vulnerabilities. 
=> Fix OS vulnerabilities for helm-cli and conformange image

.pipelines/nightly-image-scan/image-scan-job.yaml, .pipelines/nightly-image-scan/image-scan.yaml, .pipelines/templates/build-conf-test-image.yaml, .pipelines/templates/build-helm-cli-image.yaml, .pipelines/templates/install-trivy.yaml, .pipelines/templates/trivy-scan-image.yaml, Makefile
**Description**: Create a nightly job to scan helm-cli and osm-arc-conformance images for security vulnerabilities with trivy. 
=> Create nightly job for image scan

.pipelines/templates/build-conf-test-image.yaml, .pipelines/templates/publish-helm-chart.yaml
**Description**: Set boolean variables to lowercase for consistency and readability. 
=> Lowercase boolean parameters

charts/osm-arc/Chart.yaml, charts/osm-arc/templates/validate-single-mesh.yml, charts/osm-arc/values.yaml
**Description**: Update version to v1.0.0-rc.4 for osm-arc. Starting from this version, we will also be using MCR to store third party images (Grafana, Jaeger, Prometheus, etc.). 
3. grafana, grafana-image-renderer, and jaegertracing/all-in-one version in osm-arc/oss values.yaml
- Networking …
=> Update version to v1.0.0-rc.4

.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md, .pipelines/pr-job/e2e-job.yaml
**Description**: Modify release pull request template for new release process steps for v1.0, which include verifying that images for third party dependencies are in MCR for the corresponding version listed in osm-arc/oss values.yaml. 
Also change trigger for pr-e2e-job so that future github template changes don't initiate a CI run. 
- Documentation          [X]
- Other                  [X]
- Does this change contain code from or inspired by …
=> Update release template

tools/helm/Dockerfile
**Description**: Fix security vulnerabilities CVE 2021 3995 and 3996 in osm-helm-cli image
- CI System              []
=> Fix Sec Vuln 2021_3995_3996

.pipelines/upgrade-job/upgrade-e2e-job.yaml, scripts/update-extension.sh
**Description**: Change update step to use `az k8s-extension update`, and also change trigger for upgrade job so changes to add-extension.sh or update-extension.sh will run the upgrade tests. 
=> Change upgrade step

.pipelines/upgrade-job/upgrade-e2e-job.yaml, scripts/update-extension.sh
**Description**: Correct spelling for upgrade job, and test that it gets triggered. 
=> Correct spelling for upgrade

charts/osm-arc/Chart.yaml, charts/osm-arc/values.yaml
**Description**: Update version to 1.0.0
- CI System …
=> Update verion to 1.0.0

.pipelines/pr-job/e2e-job.yaml, scripts/register-extension-prod.sh
**Description**: Add script to register osm-arc extension in prod registries. 
- Other                  [X]
=> Add prod registration script

.pipelines/templates/run-upstream-e2e.yaml, charts/osm-arc/Chart.yaml
**Description**: Update osm-arc version to v1.0.0-1
- Tests …
=> Update version to v1.0.0-1

.pipelines/templates/build-helm-cli-image.yaml, tools/helm/Dockerfile
**Description**: Fix security vulnerabilities in osm-helm-cli image.
=> Fix security vulnerabilities in osm-helm-cli image.

tools/helm/Dockerfile
**Description**: Fix security vulnerabilities in osm-helm-cli image for CVE-2022-1271
=> Fix security vulnerability osm-helm-cli gzip liblzma5

tools/helm/Dockerfile
**Description**: Upgrade dpkg in osm-helm-cli to fix security vulnerability CVE-2022-1664
=> Fix sec vuln dpkg osm-helm-cli

.pipelines/templates/debug-resources.yaml
**Description**: Enhance troubleshooting steps in CI to include other osm-arc pods, helm history, azure-arc pods and deployments, kubectl events and deployments, and ensure that the helm chart version is still correct (i.e no unintended downgrades/upgrades happened since installation or upgrade). 
- Other                  [X]
- Does this change contain code from or inspired by another project? If so, did you …
=> Enhance debugging steps

.pipelines/aks-addon-nightly/e2e-aks-addon-jobs.yaml, .pipelines/templates/debug-resources.yaml
**Description**: Parameterize debugging steps so that Arc-specific commands only run for osm-arc runs and not the AKS addon nightly job. 
=> Fix aks addon debug steps

conformance/plugins/osm-arc/Dockerfile, conformance/plugins/osm-arc/conformance.yaml, conformance/plugins/osm-arc/osm_arc_conformance.sh
**Description**: Use a different go xml converter package to address the error with the XML parsing. Tested locally. 
=> Fix conformance plugin xml error

.pipelines/templates/aks-addon-templates/enable-osm-aks-addon.yaml
**Description**: Try pinning AKS preview to 0.5.87 to unblock AKS addon nightly job. 
- Tests                  []
=> pin aks-preview version 0.5.87

charts/osm-arc/templates/metrics-agent-deployment.yaml, charts/osm-arc/templates/metrics-rbac.yaml
**Description**: Change security context for SA used in metrics-agent-deployment. 
=> OpenShift: Add privileged SCC for MDM security context

charts/osm-arc/Chart.yaml
**Description**: Update osm-arc version to v1.1.1-1
- Tests …
=> update version to v1.1.1-1

conformance/plugins/osm-arc/conformance.yaml, conformance/plugins/osm-arc/osm_arc_conformance.sh
**Description**: Fix conf test retry logic for single test failure. 
=> Conf test plugin single failure

scripts/connect-to-arc.sh
Signed-off-by: nshankar <nshankar@microsoft.ghe.com>
**Description**: Unblock the connect to Azure Arc step in the CI by temporarily adding a step to install the python Crypto package. 
=> Unblock connectedk8s - install python Crypto

.pipelines/pr-job/e2e-job.yaml, .pipelines/templates/get-latest-tag.yaml, .pipelines/upgrade-job/upgrade-e2e-job.yaml, charts/osm-arc/Chart.yaml, charts/osm-arc/values.yaml, conformance/plugins/osm-arc/conformance.yaml, conformance/plugins/osm-arc/osm_arc_conformance.sh, scripts/connect-to-arc.sh
Updates versions and image tags in chart.yaml and values.yaml
=> release(v1.2.2): updating version to v1.2.2-beta-1

charts/osm-arc/Chart.yaml, charts/osm-arc/values.yaml
Updates versions and image tags in chart.yaml and values.yaml
**Release PR checklist**:
=> release(v1.2.3): updating version to v1.2.3-beta-1

charts/osm-arc/Chart.yaml, conformance/plugins/osm-arc/osm_arc_conformance.sh, scripts/install-k8s-extension.sh
Updates v1.2.3-beta-1 to v1.2.3.
**Release PR checklist**:
=> release(v1.2.3): update v1.2.3-beta-1 to v1.2.3

.pipelines/aks-addon-nightly/e2e-aks-addon-jobs.yaml, .pipelines/aks-addon-nightly/e2e-aks-addon.yaml, .pipelines/conformance-test-job/push-osm-arc-conf-plugin.yaml, .pipelines/nightly-image-scan/image-scan-job.yaml, .pipelines/pr-job/e2e-aks-arc.yaml, .pipelines/pr-job/e2e-job.yaml, .pipelines/templates/checkout-upstream-repo.yaml, .pipelines/templates/publish-helm-chart.yaml, .pipelines/templates/run-upstream-e2e.yaml, .pipelines/test-prod-job/osm-arc-prod.yaml, .pipelines/upgrade-job/upgrade-e2e-job.yaml, charts/osm-arc/Chart.yaml, charts/osm-arc/values.yaml, scripts/install-k8s-extension.sh
Description: Update chart version to 1.2.6-beta-1. 
- …
=> Update osm-arc version to 1.2.6-beta-1. 

.pipelines/aks-addon-nightly/e2e-aks-addon-jobs.yaml, .pipelines/aks-addon-nightly/e2e-aks-addon.yaml, .pipelines/conformance-test-job/push-osm-arc-conf-plugin.yaml, .pipelines/nightly-image-scan/image-scan-job.yaml, .pipelines/pr-job/e2e-aks-arc.yaml, .pipelines/templates/publish-helm-chart.yaml, .pipelines/templates/run-upstream-e2e.yaml, .pipelines/test-prod-job/osm-arc-prod.yaml, conformance/plugins/osm-arc/osm_arc_conformance.sh, scripts/install-k8s-extension.sh
**Description**: Update conf test image and staging pools. 
=> Update conf test and staging pools

conformance/plugins/osm-arc/conformance.yaml
**Description**: Update conformance image tag
=> Update conformance image

conformance/plugins/osm-arc/conformance.yaml, conformance/plugins/osm-arc/osm_arc_conformance.sh
**Description**: Updating the conformance test image to fix the k8s-extension version.
=> Update conf test image for k8s-extension version. 

conformance/plugins/osm-arc/conformance.yaml, conformance/plugins/osm-arc/osm_arc_conformance.sh
**Description**:  Add new variable to pass in GH PAT to conformance test script
=> Add new variable for conf test plugin token
